### ISSUE TITLE
Support local Json file

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [lionhylra/SwiftJSONSolution#2]
It would be nice to have the ability to load local JSON data

**Comment by lionhylra** [comment]
Sure, this feature will be added soon

**Comment by Ashraf-Ali-aa** [comment]
@lionhylra I have managed to load local json using this `file:///Users/<user>/file.json`

**Comment by lionhylra** [comment]
Wow, I didn't know that.

**Comment by Ashraf-Ali-aa** [comment]
@lionhylra one more thing, have a look at https://github.com/Ahmed-Ali/JSONExport

**Comment by lionhylra** [comment]
@Ashraf-Ali-aa Thank you for showing me this repository. This repo is a great inspiration to me. It has a better UI and supports more languages than mine. How do you think?

**Comment by Ashraf-Ali-aa** [comment]
the support for multiple languages is really nice, it also automatically adds a decent class name using json key, but one feature I really like to see is the ability to interactively convert the swift class to json, i.e have a tab that uses the generated class and the be able to provide data that outputs json like your other project.

**Comment by lionhylra** [comment]
@Ashraf-Ali-aa my app also retrieve class name from json key too, except that it can't get the name for an array. If the name is plural, the class name should be singular. I think that repo doesn't handle this well. It just change "-s" to "-", "-ies" to "-y".

In terms of converting the swift class to json, I don't see it as a common use case for now.

**Comment by lionhylra** [comment]
The feature is implemented.
